apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: hooktrigger-api
    tier: hooktrigger-api
  name: hooktrigger-api-storage
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 0.1Gi
  storageClassName: default
  nfs:
    path: /k8s/kestrel-tls
    server: 10.1.1.253
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
