apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: seq
  name: seq-pvc
  namespace: codescu
spec:
  storageClassName: default
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: seq-storage
